import asyncio
import os
import time
import edge_tts
from playwright.sync_api import sync_playwright
from moviepy import ImageClip, AudioFileClip, concatenate_videoclips
from PIL import Image, ImageDraw, ImageFont

# -- CONFIG --
VOICE        = "en-US-JennyNeural"
OUTPUT_DIR   = "demo_assets"
VIDEO_FILE   = "AutoUI_Demo.mp4"
APP_URL      = "http://localhost:8000"
WIDTH, HEIGHT = 1920, 1080

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Script scenes - each scene either types a prompt or just narrates over current view
SCENES = [
    {
        "narration": "Introducing AutoUI. The autonomous frontend designer agent. "
                     "Built for the Microsoft Agents League Hackathon, AutoUI transforms "
                     "your ideas into beautiful, production ready user interfaces, in seconds.",
        "action": "title_card",
        "label": "intro"
    },
    {
        "narration": "Let me show you how it works. "
                     "Simply describe what you want to build in plain English. "
                     "I will ask AutoUI to build an interactive comic website with dark theme and colorful panels.",
        "action": "type_prompt",
        "prompt": "Build an interactive comic website with dark theme and colorful panels",
        "label": "comic"
    },
    {
        "narration": "Within moments, AutoUI generates a complete, styled, interactive page. "
                     "Complete with navigation, colorful chapter panels, and pagination. "
                     "No code was written by hand.",
        "action": "show_result",
        "label": "comic_result"
    },
    {
        "narration": "Let us try something completely different. A dark login page with neon glow effects.",
        "action": "type_prompt",
        "prompt": "Build a dark login page with neon pink glow effects and glassmorphism card",
        "label": "login"
    },
    {
        "narration": "AutoUI understands modern design principles like glassmorphism, "
                     "neon aesthetics, and accessibility. Delivering pixel perfect results, instantly.",
        "action": "show_result",
        "label": "login_result"
    },
    {
        "narration": "One more. A futuristic analytics dashboard with live stats cards.",
        "action": "type_prompt",
        "prompt": "Design a futuristic dark analytics dashboard with stats cards showing users, revenue, and system load",
        "label": "dashboard"
    },
    {
        "narration": "Three completely different, stunning user interfaces. All generated by "
                     "a single AI agent, from plain English descriptions. "
                     "AutoUI is the future of frontend development. "
                     "Built by Swati Gupta. Thank you for watching!",
        "action": "show_result",
        "label": "outro"
    },
]

# -- STEP 1: Generate voiceover audio --
async def generate_audio(text, filename):
    communicate = edge_tts.Communicate(text, VOICE, rate="+0%")
    await communicate.save(filename)
    print(f"  [OK] Audio: {filename}")

async def generate_all_audio():
    print("\n[AUDIO] Generating voiceover audio...")
    for i, scene in enumerate(SCENES):
        path = os.path.join(OUTPUT_DIR, f"audio_{i:02d}.mp3")
        scene["audio_path"] = path
        await generate_audio(scene["narration"], path)

# -- STEP 2: Create title card --
def create_title_card():
    img = Image.new("RGB", (WIDTH, HEIGHT), color=(15, 23, 42))
    draw = ImageDraw.Draw(img)

    # Background pattern
    for x in range(0, WIDTH, 40):
        for y in range(0, HEIGHT, 40):
            draw.ellipse([x-1, y-1, x+1, y+1], fill=(25, 40, 70))

    try:
        font_big = ImageFont.truetype("arial.ttf", 80)
        font_med = ImageFont.truetype("arial.ttf", 36)
        font_small = ImageFont.truetype("arial.ttf", 28)
    except:
        font_big = ImageFont.load_default()
        font_med = font_big
        font_small = font_big

    draw.text((WIDTH//2, HEIGHT//2 - 120), "</> AutoUI",
              fill=(96, 165, 250), font=font_big, anchor="mm")
    draw.text((WIDTH//2, HEIGHT//2 - 20), "The Autonomous Frontend Designer Agent",
              fill=(203, 213, 225), font=font_med, anchor="mm")
    draw.text((WIDTH//2, HEIGHT//2 + 40), "Powered by Gemini AI",
              fill=(139, 92, 246), font=font_small, anchor="mm")
    draw.text((WIDTH//2, HEIGHT//2 + 100), "Microsoft Agents League Hackathon",
              fill=(100, 116, 139), font=font_small, anchor="mm")
    draw.text((WIDTH//2, HEIGHT//2 + 150), "Built by Swati Gupta",
              fill=(139, 92, 246), font=font_small, anchor="mm")

    path = os.path.join(OUTPUT_DIR, "title_card.png")
    img.save(path)
    print("  [OK] Title card created")
    return path

# -- STEP 3: Take screenshots by interacting with the live app --
def take_screenshots(title_card_path):
    print("\n[APP] Opening AutoUI and taking screenshots...")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": WIDTH, "height": HEIGHT})

        for i, scene in enumerate(SCENES):
            path = os.path.join(OUTPUT_DIR, f"screen_{i:02d}.png")
            scene["screen_path"] = path

            if scene["action"] == "title_card":
                # Use the pre-made title card
                import shutil
                shutil.copy(title_card_path, path)
                print(f"  [OK] Scene {i}: Title card")

            elif scene["action"] == "type_prompt":
                # Navigate to app fresh for each prompt
                page.goto(APP_URL, wait_until="networkidle")
                time.sleep(1)

                # Find the textarea and type the prompt
                textarea = page.locator("#prompt-input")
                textarea.fill(scene["prompt"])
                time.sleep(0.5)

                # Click the send button
                send_btn = page.locator("#send-btn")
                send_btn.click()

                # Wait for the AI to generate the UI (loading overlay appears then disappears)
                print(f"  [WAIT] Generating UI: {scene['prompt'][:50]}...")
                try:
                    # Wait for loading overlay to appear
                    page.wait_for_selector("#loading-overlay.flex", timeout=5000)
                    # Wait for loading overlay to disappear (generation complete)
                    page.wait_for_selector("#loading-overlay.hidden", timeout=120000)
                except:
                    # If selectors don't work, just wait a reasonable time
                    time.sleep(15)

                time.sleep(2)  # Extra time for iframe to render
                page.screenshot(path=path)
                print(f"  [OK] Scene {i}: Prompt typed + result visible")

            elif scene["action"] == "show_result":
                # Just take another screenshot of the current state (zoomed into result)
                time.sleep(1)
                page.screenshot(path=path)
                print(f"  [OK] Scene {i}: Result screenshot")

        browser.close()

# -- STEP 4: Assemble video --
def assemble_video():
    print("\n[VIDEO] Assembling final video...")
    clips = []

    for i, scene in enumerate(SCENES):
        audio = AudioFileClip(scene["audio_path"])
        duration = audio.duration + 1.0  # add 1s padding

        img_clip = ImageClip(scene["screen_path"]).with_duration(duration)
        img_clip = img_clip.resized((WIDTH, HEIGHT))
        img_clip = img_clip.with_audio(audio)
        clips.append(img_clip)
        print(f"  [OK] Scene {i+1}/{len(SCENES)}: {duration:.1f}s")

    final = concatenate_videoclips(clips, method="compose")
    final.write_videofile(VIDEO_FILE, fps=24, codec="libx264",
                          audio_codec="aac", logger=None)
    print(f"\n[DONE] Video saved: {VIDEO_FILE}")

# -- MAIN --
if __name__ == "__main__":
    print("AutoUI Demo Video Generator")
    print("=" * 50)

    # Step 1: Title card
    print("\n[TITLE] Creating title card...")
    title_path = create_title_card()

    # Step 2: Audio
    asyncio.run(generate_all_audio())

    # Step 3: Screenshots (interacts with live app)
    take_screenshots(title_path)

    # Step 4: Assemble
    assemble_video()

    abs_path = os.path.abspath(VIDEO_FILE)
    print(f"\n[COMPLETE] Done! Your video is at: {abs_path}")
