import os
import subprocess
from moviepy import AudioFileClip
import imageio_ffmpeg
import asyncio
import edge_tts

OUTPUT_DIR = "demo_assets"
VIDEO_FILE = "AutoUI_Demo.mp4"
ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()

SCENES = [
    {
        "audio": "audio_00.mp3",
        "image": "title_card.png"
    },
    {
        "audio": "audio_01.mp3",
        "image": "../screenshots/comic.png"
    },
    {
        "audio": "audio_02.mp3",
        "image": "../screenshots/comic.png"
    },
    {
        "audio": "audio_03.mp3",
        "image": "../screenshots/login.png"
    },
    {
        "audio": "audio_04.mp3",
        "image": "../screenshots/login.png"
    },
    {
        "audio": "audio_05.mp3",
        "text": "One more. A beautiful personal portfolio homepage.",
        "image": "../screenshots/portfolio.png"
    },
    {
        "audio": "audio_06.mp3",
        "text": "Three completely different, stunning user interfaces. All generated by a single AI agent, from plain English descriptions. AutoUI is the future of frontend development. Built by Swati Gupta. Thank you for watching!",
        "image": "../screenshots/portfolio.png"
    }
]

async def generate_new_audio():
    print("Generating new audio for portfolio and outro...")
    await edge_tts.Communicate(SCENES[5]["text"], "en-US-JennyNeural").save(os.path.join(OUTPUT_DIR, SCENES[5]["audio"]))
    await edge_tts.Communicate(SCENES[6]["text"], "en-US-JennyNeural").save(os.path.join(OUTPUT_DIR, SCENES[6]["audio"]))

def assemble():
    scenes_files = []
    for i, scene in enumerate(SCENES):
        audio_path = os.path.join(OUTPUT_DIR, scene["audio"])
        img_path = os.path.join(OUTPUT_DIR, scene["image"])
        out_path = os.path.join(OUTPUT_DIR, f"new_scene_{i:02d}.mp4")
        
        audio = AudioFileClip(audio_path)
        dur = audio.duration + 0.5
        audio.close()
        
        # We need to scale images to exactly 1920x1080 and pad them if necessary so ffmpeg doesn't crash on different sizes
        cmd = [
            ffmpeg_exe, "-y",
            "-loop", "1", "-framerate", "24",
            "-i", img_path,
            "-i", audio_path,
            "-vf", "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1",
            "-c:v", "libx264", "-tune", "stillimage",
            "-c:a", "aac", "-b:a", "192k",
            "-pix_fmt", "yuv420p",
            "-t", str(dur),
            out_path
        ]
        print(f"Generating scene {i}...")
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        scenes_files.append(out_path)

    list_file = os.path.join(OUTPUT_DIR, "new_list.txt")
    with open(list_file, "w") as f:
        for sf in scenes_files:
            f.write(f"file '{os.path.basename(sf)}'\n")

    concat_cmd = [
        ffmpeg_exe, "-y",
        "-f", "concat", "-safe", "0",
        "-i", list_file,
        "-c", "copy",
        VIDEO_FILE
    ]
    print("Assembling final video...")
    subprocess.run(concat_cmd)
    print("Done!")

if __name__ == "__main__":
    asyncio.run(generate_new_audio())
    assemble()
